#!/usr/bin/python3
import os
from sys import argv

#os.system(f"tunget {argv[1]}")
#os.system(f"wget biondi.co/graph.txt")
# <sizes>         ::= nr_states nr_labels nr_l_trans nr_w_trans nr_blocks

with open(f"{argv[1]}") as f:
    nodes = int(f.readline()[:-1])
    edges = int(f.readline()[:-1])
    print(f"{nodes} 0 0 {edges} 1")

    for edge in f:
        start, weight, end = list(map(int,edge.split(" ")))
        print(f"{start + 1} {weight} {end + 1}")
